# Generated by Django 2.2.12 on 2020-04-28 03:25

from django.db import migrations, models
import djongo.models.fields
import insta_down.model.data_crawl


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCrawl',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('owner', djongo.models.fields.EmbeddedField(model_container=insta_down.model.data_crawl.Owner)),
                ('data', djongo.models.fields.ArrayField(model_container=insta_down.model.data_crawl.ItemCrawl)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemCrawl',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('thumbnail', models.TextField()),
                ('countComment', models.IntegerField()),
                ('countLike', models.IntegerField()),
                ('shortcode', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('avatar', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
